# Generated by Django 3.2 on 2023-07-02 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='材料名')),
                ('amount', models.CharField(max_length=32, verbose_name='内容量')),
                ('stock_type', models.IntegerField(choices=[(1, 'Bread'), (2, 'Fruits'), (3, 'Seasoning'), (4, 'Japanese Sweets')])),
                ('stock_num', models.IntegerField(default=0, verbose_name='在庫数')),
                ('remarks', models.TextField(blank=True, verbose_name='備考')),
                ('managed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='材料管理者')),
            ],
        ),
    ]
