# Generated by Django 3.2 on 2023-07-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='材料名')),
                ('amount', models.CharField(max_length=32, verbose_name='内容量')),
                ('stock_type', models.IntegerField(verbose_name='種類')),
                ('stock_num', models.IntegerField(verbose_name='在庫数')),
                ('remarks', models.TextField(blank=True, verbose_name='備考')),
            ],
        ),
    ]
