# Generated by Django 3.2 on 2023-07-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_num',
            field=models.PositiveIntegerField(default=0, verbose_name='在庫数'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_type',
            field=models.IntegerField(choices=[(1, 'Bread'), (2, 'Fruits'), (3, 'Seasoning'), (4, 'Japanese Sweets')], verbose_name='種類'),
        ),
    ]
