# Generated by Django 3.2 on 2023-10-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20230702_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('lat', models.CharField(max_length=32, verbose_name='lat')),
                ('lng', models.CharField(max_length=32, verbose_name='lng')),
            ],
        ),
    ]
